### ISSUE TITLE
IMPORTANT - tag names

### ISSUE THREAD

**Issue by franfranfranfran** [apb165/ColmarAcademy#2]
https://github.com/apb165/ColmarAcademy/blob/master/index.html#L148
https://github.com/apb165/ColmarAcademy/blob/master/index.html#L139

startlearning_section, practicing_section, and several others on the page are not valid tag names. heres a list of html tags you can use - https://www.w3schools.com/tags/default.asp

**Comment by apb165** [comment]
Changed to divs
